= Bonjour, AsciiDoc!
Doc Writer <doc@example.com>
:toc: left
:toc-title: Table des matières

Une introduction à http://asciidoc.org[AsciiDoc].

essai de documentation

== Première Partie

=== des listes

* item 1
* item 2

NOTE: An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is determined by the label
at the beginning of the paragraph.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...

== Deuxième Partie

=== Inclure du code

du code pour essai

.Exemple
----
$ c'est du code
essai

# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 698,7G  0 disk 
├─sda1   8:1    0  19,9G  0 part /
├─sda2   8:2    0  19,9G  0 part 
├─sda3   8:3    0     1K  0 part 
├─sda5   8:5    0   5,5G  0 part [SWAP]
└─sda6   8:6    0 653,3G  0 part /home
sr0     11:0    1  1024M  0 rom
----


=== autre listes

. liste 1
.. sousliste a
.. sousliste b
. liste 2
. liste encore
.. sousliste a
.. sousliste b
.. sousliste c

=== Avec Latex

- latexmath:[$R_x = 10.0 \times \sin(R_\phi)$]

[TIP]
====
un essai avec tip
====

WARNING: un essai avec note…

=== autres mises en forme

du texte *en gras* ou en _italique_ ou #bien# **consi**déra**__ble__**ment 3^2^ et d~1~, d~2~^4^

du texte [.underline]souligné en partie

[source,ruby]
puts "Hello, World!"

